<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Lista de usuarios MailChimp</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
              integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <style>
            body {
            }

            h1,h2,h3 {
                text-align: center;
                color: #aaaaaa;
                font-family: 'Lato', sans-serif;
                font-size: 80px;
                font-weight: 400;
            }

            h2,h3 {
                color: #bdbebb;
                font-size: 50px;
                font-weight: 200;
                margin-top: 10px;
            }

            h3{
                font-weight: 100;
                font-size: 25px;
            }

             .bg-danger {
                padding:5px 10px;
                margin:20px 5px;
                border-radius: 5px;

            }
            .cont_loader{
                margin: 0 auto;
                display: block;
                width: 40px;
            }
            .loader {
                border: 5px solid #f3f3f3;
                border-radius: 50%;
                border-top: 5px solid #aaaaaa;
                width: 40px;
                height: 40px;
                -webkit-animation: spin 1s linear infinite; /* Safari */
                animation: spin 1s linear infinite;
            }

            /* Safari */
            @-webkit-keyframes spin {
                0% { -webkit-transform: rotate(0deg); }
                100% { -webkit-transform: rotate(360deg); }
            }

            @keyframes spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
            }
            #modal h1 {
                font-size: 40px;
            }
            #modal h3 {
                font-size: 18px;
            }

        </style>
    </head>
    <body>
        <h1>Lista de usuarios</h1>
        <h2>MailChimp</h2>

        <div class="contaniner">

                <div class="col-sm-6  col-sm-offset-3 ">
                    <?php
                    if(isset($mensajes['info'])) { ?>
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <?php
                            foreach($mensajes['info'] as $mensaje) {
                                echo "<p>$mensaje</p>";
                            }
                            ?>
                        </div>
                    <?php } ?>

                    <?php
                    if(isset($mensajes['error'])) { ?>
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <?php
                            foreach($mensajes['error'] as $mensaje) {
                                echo "<p>$mensaje</p>";
                            }
                            ?>
                        </div>
                    <?php } ?>

                    <form class="form-horizontal" method="post" id="form">

                        <div class="form-group">
                            <label for="user" class="col-sm-2 control-label">Usuario:</label>
                            <div class="col-sm-10">
                             <input class="form-control" placeholder="Usuario" id="user" type="text" name="user" value="">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password" class="col-sm-2 control-label">Contraseña:</label>
                            <div class="col-sm-10">
                                <input class="form-control" placeholder="Contraseña" id="password" type="password" name="password">
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button class="btn btn-default" type="button" value="1">Login</button>
                            </div>
                        </div>
                    </form>

                    <p class="text-center"><a href="/usuario/new">Registrarse</a></p>
                </div>
        </div>


        <div id="modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        <p>One fine body&hellip;</p>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->


        <script
                src="https://code.jquery.com/jquery-3.3.1.min.js"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script>

    </script>
    </body>
</html>
